### PR TITLE
Feature/161552771 create endpoint for experiment card

### PR DESCRIPTION
**Pull request by lingyun1010**
This work is based on Monica's popular species branch not on the latest dev branch. 

This one provides a new endpoint for landing page cards which using Monica's [Atlas homepage card](https://github.com/ebi-gene-expression-group/atlas-homepage-cards) component. This work is used in [SC landing page](https://github.com/ebi-gene-expression-group/scxa-experiment-landing-page/tree/feature%2F161087328-design-HCA-landing-page) branch to list all the experiments in HCA or requested experiment accessions.

An integrated test has been implemented for `JsonLandingCardController`.

### CODE REVIEW

**Comment by monicajianu** [comment]
@lingyun1010 It looks like your Bamboo build is failing http://bar:8085/browse/ATLAS-SCXACI8 Please investigate and make the appropriate changes. You should get in the habit of making sure you have green builds before opening a PR.

**Comment by lingyun1010** [comment]
@monicajianu Yes. Actually I only run the `JsonLoadingPageControllerWIT` which passed. This branch is based on the popular species branch <http://bar:8085/browse/ATLAS-SCXACI1>, which is failed in test. Could you please have a look?

**Comment by monicajianu** [comment]
@lingyun1010 My branch is failing due to different reasons (I have now fixed those). If you check the logs for the Bamboo build for your branch, it is complaining about compilation issues that have nothing to do with the popular species branch.

**Comment by lingyun1010** [comment]
I have reimplement this work in a new branch, since it is quite messy due to rebase. Please have a review of the new one, which passed the test.

**Pull request closed without merging**
